node_js:
- "1"
- "2"
language: node_js
script: "npm run test-ci"
before_install:
  - curl http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz | sudo tar -C /usr/local/bin/ -xJ --strip-components=1
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
